name: Publish documentation

on:
  push:
    branches:
      - main
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: uv sync --no-dev --group doc

      - name: Build doc
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "docs.deploy@heva-data.com" 
          uv run mike deploy --config-file mkdocs.yaml -u --push $(uv version --short) latest 
